### ISSUE TITLE
@Cache condition不支持返回结果是否为空,是否为true等判断吗？

### ISSUE THREAD

**Issue by beyond-up** [qiujiayu/AutoLoadCache#107]
@Cache(expire = 60 * 30, key = "serviceName", hfield = "'#args",
            argumentsDeepcloneEnable = false, condition= "#Result.success")

**Comment by beyond-up** [comment]
Result是接口返回结果类， private Boolean success; // success 请求状态

**Comment by beyond-up** [comment]
@Cache(expire = 60 * 30, key = "serviceName", hfield = "'#args",
argumentsDeepcloneEnable = false, condition= "#retVal.success")  也不行，报错：org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'success' cannot be found on null

**Comment by beyond-up** [comment]
@Cache(expire = 60 * 30, key = "serviceName", hfield = "'#args",
argumentsDeepcloneEnable = false, condition= "#retVal.isSuccess()") 也不行

**Comment by qiujiayu** [comment]
condition 是不支持的。
