### ISSUE TITLE
为什么分了这么多包，有什么好处吗？

### ISSUE THREAD

**Issue by gyl-coder** [qiujiayu/AutoLoadCache#109]
![image](https://user-images.githubusercontent.com/33021341/147999585-a9a52f04-8f0e-49fa-930e-666a35650821.png)

请教一下，项目中这些模块为何这么分包，有什么依据吗？  是基于哪方面考虑的呢？

**Comment by qiujiayu** [comment]
lock 主要是用于对分布式锁的实现。cache-mananger 是用于对缓存管理的实现。
