### ISSUE TITLE
有没有这么种方案的解决配置. 感觉能省redis的内存. 多套缓存只保留根据id的,其他关联查询,都缓存关联关系

### ISSUE THREAD

**Issue by ilaotan** [qiujiayu/AutoLoadCache#111]
https://legacy.go-zero.dev/cn/sql-cache.html

**Comment by gundamff** [comment]
上面url 404 了

**Comment by ilaotan** [comment]
> 上面url 404 了
它网站改版了. 老地址是这个
https://legacy.go-zero.dev/cn/sql-cache.html

**Comment by ilaotan** [comment]
简单来说,就是主键缓存 ,存储全部数据. 其他非主键的查询, 只缓存对应的主键id, 然后根据主键id,再查一下缓存

**Comment by gundamff** [comment]
你看看Magic模式， 实现的就是这个效果
