### ISSUE TITLE
学习项目中遇到的一点问题

### ISSUE THREAD

**Issue by 1308014800** [qiujiayu/AutoLoadCache#123]
学生一个，可能问题有点稚嫩。
请问自动加载和异步刷新是不是同一种意思？我看源码中AutoLoadHandler和RefreshHandler中最后都是通过DataLoader加载数据和cachehandler.writeCache方法去写入缓存，此方法通过CacheManager去实际写入缓存。
这两个Handler的处理过程有点类似，让我有些疑惑自动加载和异步刷新的区别，我阅读代码的理解好像这两者都是根据时间去更新缓存数据，具体有什么区别呢？问题有点幼稚，望海涵。

**Comment by qiujiayu** [comment]
异步刷新：是依赖调用的，如果长时间没有调用，就会造成缓存不刷新。
自动加载：不依赖调用。
