### ISSUE TITLE
maven 仓库没有最新版本的 7.2.1 版本，可以上传一下吗？

### ISSUE THREAD

**Issue by yisshengyouni** [qiujiayu/AutoLoadCache#129]
如题

**Comment by qiujiayu** [comment]
https://repo1.maven.org/maven2/com/github/qiujiayu/ 一直都是有的

**Comment by yisshengyouni** [comment]
> https://repo1.maven.org/maven2/com/github/qiujiayu/ 一直都是有的

知道原因了，刚开始引用的是 all-in-one 的那个autoload-cache 包
后面的新版本把包拆分了
