### ISSUE TITLE
使用jdkSerializer时，依然需要引用hessian相关的包

### ISSUE THREAD

**Issue by qinerg** [qiujiayu/AutoLoadCache#13]
AbstractCacheManager 类中默认使用了 HessianSerializer ，所以即使使用 jdkSerializer 也必需加载 HessianSerializer 相关的包。
建议默认JdkSerializer 或 StringSerializer

**Comment by qinerg** [comment]
同样，SpringELParser 也是默认的，就算使用 JavaScriptParser 也必须引用 SpringEL 相关包。

**Comment by qiujiayu** [comment]
代码已经修改。
