### ISSUE TITLE
建议将表达式引擎生成的key打印出来

### ISSUE THREAD

**Issue by qinerg** [qiujiayu/AutoLoadCache#14]
使用者如对表达式引擎不熟悉的话，对于框架自动生成最终的缓存key值不是很笃定，生成的key值可能不是最优的。
同时也为了方便缓存调试，建议将key中使用表达式引擎后自动生成的key值，通过日志打印出来，方便优化。

**Comment by qiujiayu** [comment]
不建议在代码中打太多的日志，日志多了，返而不容易查找问题，这块自己写单元测试就很容易解决问题。

**Comment by qinerg** [comment]
个人感觉应该加上日志，哪怕日志的级别低一些（如trace）。
实际使用中，用户会根据实际情况屏蔽掉一些包的日志。但如果没有日志，则不方便定位于问题。

**Comment by qiujiayu** [comment]
表达式解析如果要调试，还要打印它的上下文，不然打出来的日志意义也不大，这样一来打印的东西就变多了。从我个人经验来说，表达式都会写得非常简单明了，可以不需要调式就能看明白。

**Comment by qinerg** [comment]
不用考虑上下文吧，那样就扩大化了。主要是基本信息也没有。我认为打印key有几方面用处：
1、调优缓存key；
2、发现bug，需要手工维护缓存时，能够直接看到key值，而不需自己推断；
表达式可能很长，因为需要做空值判断的，否则可能会有空指针问题。
没事，如果楼主觉得影响了性能不合适可以不加。反正是开源的，可以自行调整的
