### ISSUE TITLE
javax.script.ScriptException: <eval>:1:166 Expected an operand but found error

### ISSUE THREAD

**Issue by lihui-ppg** [qiujiayu/AutoLoadCache#18]
@Cache(expire=0, key="'user_'+args[1]", condition="args[0]=='userToken'&&#retVal!=null") 
现在过滤条件是两个但返回值条件老不识别，去掉#号与不去都不识别
![image](https://cloud.githubusercontent.com/assets/19601631/17545689/d01bf9a4-5f10-11e6-82dc-a7a940d1ed8c.png)
都是这个错

**Comment by qiujiayu** [comment]
condition中是取不到retVal的，这个条件是在执行“方法”前判断的。
