### ISSUE TITLE
AbstractCacheManager类的loadData方法加锁问题

### ISSUE THREAD

**Issue by jxqlovejava** [qiujiayu/AutoLoadCache#2]
同一个VM实例内所有穿透Cache的请求都会调用loadData方法，而loadData方法内部有三处在竞争同一个锁lock，这在高并发场景下很容易导致“锁等待”问题。不知道作者是否有做过性能方面的测试？

**Comment by qiujiayu** [comment]
这块可以优化一下，但性能影响比较小。我会在下个版本中进行优化，感谢您提供的问题。

**Comment by qiujiayu** [comment]
代码已经重新优化了。
