### ISSUE TITLE
能否在Cache类中加一个String 的 type 属性

### ISSUE THREAD

**Issue by ming300** [qiujiayu/AutoLoadCache#24]
在我们自己的业务中，需要根据某些操作去清除一批缓存，如果单纯一个key去清除效率又不高，
能否对Cache类进行一个扩展，加入String type() 属性，以便，我们自己能够根据这些type去记录相关的key，并基于type做缓存的清除操作。

**Comment by qiujiayu** [comment]
你是想做批量删除？同在已经支持了。
还是你想在查询数据的同时去删除一些缓存？

**Comment by qiujiayu** [comment]
或者你把需求发到QQ群里，大家和你一起分析一下，看看什么更好的解决方案。

**Comment by hailin0** [comment]
抽时间写了一个，稍后push上来

**Comment by hailin0** [comment]
https://github.com/qiujiayu/AutoLoadCache/commit/036cb50436e464553c8143728088f9baa82f03c7
