### ISSUE TITLE
spring boot 的栗子里面的配置怎么都是集群的啊？

### ISSUE THREAD

**Issue by ExtremeYu** [qiujiayu/AutoLoadCache#27]

**Comment by qiujiayu** [comment]
可以参考：https://github.com/qiujiayu/AutoLoadCache-spring-boot 这个例子。
现在还没写spring boot starter。等有时间再补上。

**Comment by ExtremeYu** [comment]
单机的怎么配置呢

**Comment by qiujiayu** [comment]
把AbstractCacheManager 的实例换用 com.jarvis.cache.map.CachePointCut

**Comment by qiujiayu** [comment]
https://github.com/qiujiayu/autoload-cache-spring-boot-starter spring boot starter已经开发完成，里面也有demo。

**Comment by ExtremeYu** [comment]
good
