### ISSUE TITLE
部分配置项写死问题

### ISSUE THREAD

**Issue by jxqlovejava** [qiujiayu/AutoLoadCache#3]
部分配置项，比如AbstractCacheManager.loadData()里的500ms等待时间，AutoLoadRunnable.run() 里的10ms（效率比较高的请求标准 ），这些建议作者抽出来作为可配置项。虽然有“约定优先于配置的说法”，但对于不同的线上系统，对响应时间的要求是不一样的，所以允许用户自由配置是必要的。

**Comment by qiujiayu** [comment]
建议不错，已经做成可配置。

**Comment by qiujiayu** [comment]
代码已经修改了。

**Comment by qiujiayu** [comment]
代码已经提交。
