### ISSUE TITLE
源码下载下来报错啊

### ISSUE THREAD

**Issue by Penn2017** [qiujiayu/AutoLoadCache#31]

**Comment by qiujiayu** [comment]
哪里报错？

**Comment by Penn2017** [comment]
![Uploading image.png…]()

**Comment by Penn2017** [comment]
![e3ca7be6-ab90-4a8b-9860-8d66058d9588](https://cloud.githubusercontent.com/assets/23287764/26439226/cbf2b27e-4159-11e7-96b2-f3bb33f8ef52.jpg)

图中标注的类里面

**Comment by qiujiayu** [comment]
使用Eclipse 和 IntelliJ IDEA 时，需要先安装lombok
