### ISSUE TITLE
支持多级缓存么

### ISSUE THREAD

**Issue by wenzuojing** [qiujiayu/AutoLoadCache#34]
支持多级缓存么，如进程级local cache

**Comment by qiujiayu** [comment]
支持，你可以看一下：https://github.com/qiujiayu/AutoLoadCache/blob/master/src/main/java/com/jarvis/cache/ComboCacheManager.java

**Comment by klaus-pd** [comment]
多级缓存的更新机制能参考J2cache一样，远程缓存更新之后通过广播的方式通知本地缓存更新吗？
