### ISSUE TITLE
能否支持通过命名空间的方式进行被动批量过期

### ISSUE THREAD

**Issue by 654894017** [qiujiayu/AutoLoadCache#35]
key =  namespace + key 

namespace  当作一个计数器的key ，当要失效这个命名空间下的所有value的时候，直接把namespace 对应的值加1，这样这个命名空间下的所有value就被动都失效了。

例如：
key = "menu"+"userId" 
“menu” 对应在缓存对应的value = 1.

key = “1”+ “userId1”；

失效时：
cache.incr("menu")  -->   menu -->2

key = "2"+"userId1"

**Comment by qiujiayu** [comment]
你是什么场景需要做这样的处理呢？
现在namespace只支持手动去修改。

**Comment by 654894017** [comment]
比如说每个用户的对应的菜单是不一样的。如果修改了菜单信息，我需要让所用用户的菜单信息的所有缓存失效。
namespace  的值是一个数值(incr)，也是保存到缓存里面的 ，当需要情况所有缓存时，我把namesapce的计数器值加1，这样所有这个namesapce下的缓存就都找不到了，被动的被失效了。

**Comment by 654894017** [comment]
会带来的一个问题就是，读取一个key的时候需要读取两次缓存，才能拿到这个value  先读namesapce  在读namesapce + userId

**Comment by qiujiayu** [comment]
用key + hfield 就能实现你的需求。
