### ISSUE TITLE
参数list导致key一致问题

### ISSUE THREAD

**Issue by unbendingWind** [qiujiayu/AutoLoadCache#39]
我用autoload-cache-spring-boot-starter-master框架里面的test文件夹里面进行调试，原有的数据测试确实没问题，我后来有新增了一些方法进行测试
# controller添加
`  @RequestMapping("/queryUsers1")
    public List<UserDO> queryUserList1(){
        List<Integer> idList = new ArrayList<>();
        idList.add(10);
        idList.add(11);
        return userService.queryUserList(idList);
    }

    @RequestMapping("/queryUsers2")
    public List<UserDO> queryUserList2(){
        List<Integer> idList = new ArrayList<>();
        idList.add(10);
        idList.add(11);
        idList.add(12);
        return userService.queryUserList(idList);
    }`
# **service**
`    @Override
    public List<UserDO> queryUserList(List<Integer> idList) {
        return userMapper.getUsers(idList);
    }`
# **mapper**
`    @Cache(expire=300, expireExpression="null==#retVal ? 60: 300", key="'user:getUsers:'")
    List<UserDO> getUsers(List<Integer> idList);`
# xml
进行循环插入和循环查询(ps 提交后代码显示不全)
`  <select id="getUsers" parameterType="list" resultMap="UserResultMap">
    select
    <include refid="columns" />
    from user
    where id in
    <foreach collection="list" index="index" item="item" open="(" separator="," close=")">
       #{item}
    </foreach>
  </select>

  <insert id="addUser" parameterType="com.jarvis.cache.demo.entity.UserDO" useGeneratedKeys="true" keyProperty="id">
    insert into user(name, password, age) 
    values(#{name}, #{password}, #{age})
  </insert>`

# 我测试的是一个方法传递list参数，但是list里面的值并不确定，然后进行测试http://localhost:8080/user/queryUsers1和http://localhost:8080/user/queryUsers2发现redis结果只能有一个key，这种情况如何解决？

**Comment by qiujiayu** [comment]
你那缓存key冲突了，需要调整一下。

@Cache(expire=300, expireExpression="null==#retVal ? 60: 300", key="'user:getUsers:'+#hash(#args)") List<UserDO> getUsers(List<Integer> idList);

**Comment by unbendingWind** [comment]
![1](https://user-images.githubusercontent.com/15900140/32032981-7389887c-ba3c-11e7-8a8c-7bfade9969e5.png)

`@Cache(expire=300, key="'user:getUsers:'+#hash(#args)")
    List<UserDO> getUsers(List<Integer> idList);`
这种配置方式，然后我调用springboot默认的方式，发现进入了ognl进行解析，然后就报错了

**Comment by unbendingWind** [comment]
经过代码调试发现每次key进行解析都是ognl,按照上诉参数发现一直报null，导致没有走缓存，后对AutoloadCacheManageConfiguration类下的ognlPresent直接改成false，然后才走的springEL,然后缓存正常。不知道这样理解对不对
