### ISSUE TITLE
采用继承的方式如何来设置CacheDelete呢

### ISSUE THREAD

**Issue by zhaopengme** [qiujiayu/AutoLoadCache#4]
是这样 set 的 cache,
```
    @Cache(expire=6000)
    public T get(Class t, Long id) {
        return (T) dao.unique(t, id);
    }
```
 在 update的时候,需要怎么用`@CacheDelete`呢
```
    public void update(T t) {
        dao.updateById(t);
    }
```

**Comment by qiujiayu** [comment]
当@Cache没有设置key值时，使用的是默认缓存Key，所以你这个方法：
@CacheDelete({@CacheDeleteKey(cls=DAO.class, method="get", argsEl={"#args[0].class", "#args[0].id"}, keyType=CacheKeyType.DEFAULT)})
public void update(T t) {
        dao.updateById(t);
    }

建议尽量使用自定义缓存Key:
@Cache(expire=6000, key="'KEY_'+#args[0].name+'_'+#args[1]")
    public T get(Class t, Long id) {
        return (T) dao.unique(t, id);
    }
@CacheDelete({@CacheDeleteKey(value="'KEY_'+#args[0].class.name+'_'+#args[0].id", keyType=CacheKeyType.DEFINED)})
public void update(T t) {
        dao.updateById(t);
    }

**Comment by zhaopengme** [comment]
好的,谢谢.

**Comment by qiujiayu** [comment]
最新的代码已经提交了，你可以同步一下。
