### ISSUE TITLE
redis集群下报错：MOVED 9300 127.0.0.1:7001

### ISSUE THREAD

**Issue by KevinGZ2017** [qiujiayu/AutoLoadCache#41]
ERROR com.jarvis.cache.redis.ShardedJedisCacheManager ShardedJedisCacheManager:178 get - MOVED 9300 127.0.0.1:7001
请问是哪里出问题了吗？

**Comment by qiujiayu** [comment]
从这报错来看你使用的RedisCluster,应该使用JedisClusterCacheManager

**Comment by KevinGZ2017** [comment]
问题已经解决，非常感谢你在百忙之中给予解答，会一直关注并支持你！！
