### ISSUE TITLE
Integrate with spring data and mybatis

### ISSUE THREAD

**Issue by neoqing** [qiujiayu/AutoLoadCache#43]
Hi,
      If we are using spring data and mybatis, in our case, we only have an interface definition, no DAO implementation class in our code, is it possible to use AutoLoadCache?

**Comment by qiujiayu** [comment]
yes, this is a demo https://github.com/qiujiayu/autoload-cache-spring-boot-starter/tree/master/src/test/java/com/jarvis/cache/demo/mapper

**Comment by neoqing** [comment]
Thanks for information
