### ISSUE TITLE
缓存管理页面移除了吗？

### ISSUE THREAD

**Issue by KevinGZ2017** [qiujiayu/AutoLoadCache#44]
你好，请问你把缓存管理页面和缓存管理的Servlet移除掉了吗？

**Comment by qiujiayu** [comment]
是的，后期想移到https://github.com/qiujiayu/autoload-cache-spring-boot-starter

**Comment by qiujiayu** [comment]
已移到https://github.com/qiujiayu/autoload-cache-spring-boot-starter
