### ISSUE TITLE
缓存序列化和反序列化的问题

### ISSUE THREAD

**Issue by neoqing** [qiujiayu/AutoLoadCache#45]
Hi，你好
 不知道默认序列化和反序列化是否是使用hessian？现在我的情况是在父类里面定义了一个a field，它有一个annotation org.springframework.data.annotation.Transient ，然后在子类里面重新定义了这个a field 不过没有Transient 这个annotation，问题描述
从数据库读取该对象（子类）时a field是有值的 （从API 返回的JSON上读取到），之后就进入了cache，下次读取就是从cache中读取，此时API 返回的JSON中a field是null。
如果是直接在子类上给a field 加Transient，则不管数据库还是cache都不会返回值
请问是使用方法上有问题，还是Hessian 有bug？谢谢

**Comment by neoqing** [comment]
使用JdkSerializer 后此问题目前暂未复现

**Comment by qiujiayu** [comment]
你按 https://github.com/qiujiayu/AutoLoadCache/blob/master/src/test/java/com/test/hessian/HessianTest.java 这个例子写个单元测试看看。
