### ISSUE TITLE
关于时间过期数据缓存的疑问

### ISSUE THREAD

**Issue by Rekoe** [qiujiayu/AutoLoadCache#5]
数据缓存设置了时间过期
但如果我有个条件 查询多条数据的时候 正好其中的某条（或者某些条）由于过期 在内存中没有了，那以后再有这种查询的时候 如何处理 才能得到符合条件的数据

重新load ？
还是设置过期时间为0？

**Comment by Rekoe** [comment]
比如 我有个查询
```
select * from xxx;
```
如果根据缓存时间 某些数据由于过期 在内存中被清理掉了
那以后如果我还有 这个查询的时候 ，内存中如何得到那些过期被移除的数据？

**Comment by qiujiayu** [comment]
缓存过期后，就会重新加载数据
