### ISSUE TITLE
关于@Transactional和@Cache注解同时使用时的问题

### ISSUE THREAD

**Issue by JarkimZhu** [qiujiayu/AutoLoadCache#50]
```java
        Class<?> cls=AopUtil.getTargetClass(invocation.getThis());
        Method method=invocation.getMethod();
        if(!cls.equals(invocation.getThis().getClass())) {
            logger.debug(invocation.getThis().getClass() + "-->" + cls);
            return invocation.proceed();
        }
````

请问这段逻辑的作用是什么啊？我在项目中，这段if为真，所以总是没有执行CacheMethodInterceptor里的逻辑，断点跟踪发现我有两个InterceptionAdvice，截图如下：
![qq 20180614145700](https://user-images.githubusercontent.com/1670426/41396434-7d9f11f8-6fe3-11e8-9ed3-f93729f5dd31.png)
这个问题是怎么引起的？如何解决？

**Comment by qiujiayu** [comment]
我又重新测了一下，加了@EnableTransactionManagement后存在bug。代码已提交了，麻烦验证一下，是否解决你的问题。
