### ISSUE TITLE
源码调试的时候，发现出现循环依赖

### ISSUE THREAD

**Issue by edagarli** [qiujiayu/AutoLoadCache#51]
<img width="1095" alt="2018-06-19 15 07 39" src="https://user-images.githubusercontent.com/5710228/41581881-a0e84ef2-73d2-11e8-821d-f55e230c0255.png">

**Comment by qiujiayu** [comment]
在什么情况下出现的？

**Comment by edagarli** [comment]
项目启动的时候，然后debug模式，见源码图。

<img width="1015" alt="2018-06-19 16 29 55" src="https://user-images.githubusercontent.com/5710228/41585946-11e1a6de-73de-11e8-9080-3a33183e9b00.png">

**Comment by qiujiayu** [comment]
这些还无法定位问题，希望能加入到QQ群中，提供更多信息。

**Comment by edagarli** [comment]
debug启动项目，断点断到图中ConstructorResolver catch的地方就知道了。不过不影响使用。

**Comment by edagarli** [comment]
好。
另外弱弱的问个问题，
mybatis是通过JDK的动态代理方式。 然后项目里面如果设置用的是cglib代理，这样会导致二次代理。
我复制了代码，结果启动发现一个mapper查询cache拦截器拦截两次了，感觉二次代理了。

**Comment by qiujiayu** [comment]
这个问题我之前也遇到过，但最近无法复现了。如果能提供你的测试代码，我这边能更方便测试。
