### ISSUE TITLE
关于多key批量查询，有什么好的解决方案？

### ISSUE THREAD

**Issue by wozhaosini** [qiujiayu/AutoLoadCache#54]
经常会有这样的场景：执行批量查询操作，先从缓存中批量查询，然后部分key在缓存中，这时会获取到未命中缓存的key，然后再批量去查下db，然后把db返回的数据刷入缓存，请问这种场景，有什么好的解决方案？

**Comment by qiujiayu** [comment]
这块还没有想到好的方案。

**Comment by qiujiayu** [comment]
最新版本增加了magic模式，用于解决这个问题
