### ISSUE TITLE
关于框架整合

### ISSUE THREAD

**Issue by Rekoe** [qiujiayu/AutoLoadCache#6]
作者是否可以出个和nutz 框架整合的demo？

**Comment by qiujiayu** [comment]
对nutz不了解呢，如果你有兴趣，可以根据原理写重构一下。

**Comment by qiujiayu** [comment]
AutoloadCache 4.0 已经发布了，希望对你整合nutz有帮助。 
详细代码，请参考：src/main/java/com/jarvis/cache/aop/ 中的代码，如有疑问，可以在QQ群中进行沟通。

**Comment by Rekoe** [comment]
@qiujiayu 
感谢
