### ISSUE TITLE
正常业务逻辑下的warn级别日志

### ISSUE THREAD

**Issue by realoldroot** [qiujiayu/AutoLoadCache#60]
https://github.com/qiujiayu/AutoLoadCache/blob/2345072b804caf07aef56a6e77aa2d63a94fb924/src/main/java/com/jarvis/cache/CacheHandler.java#L327
加了`@CacheDeleteTransactional`注解的方法内，因为校验等逻辑并没有走到删除缓存的步骤就结束了方法。没有通过抛异常的方式return，而是通过return code来处理，，`Set<CacheKeyTO> set`就是空的，然后就有`warn`级别的日志。

**Comment by qiujiayu** [comment]
没明白，要解决什么问题？是想当key set为empty时，抛异常吗？

**Comment by realoldroot** [comment]
是我没有说清楚:anguished:
建议：这条警告日志级别调低
问题：因为我在使用的过程中查询发现了大量`proceedDeleteCacheTransactional: key set is empty!`警告日志，查询后发现是一些被`@CacheDeleteTransactional`标注的方法并没有执行完，中间逻辑判断的时候就跳出方法，之后方法内后续调用`@CacheDelete`的语句并没有执行，所以出现了警告日志。

**Comment by qiujiayu** [comment]
你建议是使用级别？

**Comment by realoldroot** [comment]
没执行完方法跳出，key set is empty 应该是一个正常情况，warn 日志是不是不合适
