### ISSUE TITLE
怎么批量删除以XX为前缀的key？

### ISSUE THREAD

**Issue by 21jhf** [qiujiayu/AutoLoadCache#66]
@CacheDelete({@CacheDeleteKey(value="checkpackageitem-*",condition = "null != #retVal")})

写成XXX*的key，删不掉XXX前缀的所有key，应该怎么做？谢谢

**Comment by qiujiayu** [comment]
不建议这样使用，对性能影响比较大，建议增加 hfield 来管理缓存，参考如下说明：

https://github.com/qiujiayu/AutoLoadCache/blob/master/doc/deleteCache.md
