### ISSUE TITLE
Magic模式不支持Protocol Buffers协议

### ISSUE THREAD

**Issue by realoldroot** [qiujiayu/AutoLoadCache#67]
1. 实现了`ISerializer`接口，使用protobuf序列化。
2. 序列化的时候使用protobuf序列化数据。
3. 普通反序列化的时候可以根据`returnType`找到对应的类反序列化。
4. Magic模式下，方法的返回类型是`java.util.List`，类型擦除后无法得知泛型的具体类型，无法反序列化。

- 有啥解决办法吗，或者思路。

**Comment by qiujiayu** [comment]
请问你用的是哪个版本。

这个问题在使用JSON 序列化时也遇到了，现在的解决办法不是很优雅。
请参考：https://github.com/qiujiayu/AutoLoadCache/blob/master/src/main/java/com/jarvis/cache/MagicHandler.java

中 public Object magic() throws Throwable 方法内的：“为了解决使用JSON反序列化时，缓存数据类型不正确问题” 注释内容。

为了更好复现问题，是否可以把你的 protobuf序列化实现提上来？

**Comment by realoldroot** [comment]
#68

**Comment by qiujiayu** [comment]
我分析了一下你的代码，主要问题还是因为序列化方式和返序列化方式不一样造成的，已经提交一版本了，你先测一测。

**Comment by realoldroot** [comment]
经测试可以成功反序列化了。还是对反射的学习不够多，十分感谢。

**Comment by qiujiayu** [comment]
我个人觉得代码还有很大的优化空间：比如：writePool 和 readPool 可能造成内存的浪费，如果有几个大对象，那么会一直占用非常大的内存。

**Comment by realoldroot** [comment]
当时的想法是为了在序列化的时候减少对象的创建，减少GC，就使用对象池，根据业务需求固定了`WriteByteBuf`的长度，在序列化消息的时候可以反复使用这块内存。
写池目前最大内存会达到8*1m左右。
你说的大对象指的是对象池里的对象吗。

**Comment by qiujiayu** [comment]
是的

**Comment by qiujiayu** [comment]
我又改了一版，你再测测。

**Comment by realoldroot** [comment]
测试可以使用:+1:
另外我想问一下序列化对象池这一块，有什么优化思路吗，比如说动态扩容？
或者说对象池的使用意义是否大于频繁的实例化而带来的GC。

**Comment by qiujiayu** [comment]
弊大于利，两个理由：1. 使用对象池会增加锁同步问题 ； 2. 大对象造成内存不可回收问题；
内存这块可以尝试使用堆外内存，来减少GC；尽量要达到不动态扩容：

`    public byte[] serialize(CacheWrapper<Object> obj) throws Exception {
        Object cacheObj = obj.getCacheObject();
        byte[] data = null;
        if (cacheObj instanceof Message) {
            Message message = (Message) cacheObj;
            data = message.toByteArray();
        } else if (cacheObj != null) {
            data = MAPPER.writeValueAsBytes(cacheObj);
        }
        val byteBuf = new WriteByteBuf(12 + data.length);
        byteBuf.resetIndex();
        byteBuf.writeInt(obj.getExpire());
        byteBuf.writeLong(obj.getLastLoadTime());
        byteBuf.writeBytes(data);
        val bytes = byteBuf.readableBytes();
        writePool.returnObject(byteBuf);
        return bytes;
    }`

**Comment by realoldroot** [comment]
谢谢:smile:
