### ISSUE TITLE
拿来主交机制中，多个请求并发访问redis，怎么保证只选取一个leader去更新缓存

### ISSUE THREAD

**Issue by yufenggao** [qiujiayu/AutoLoadCache#72]
拿来主交机制，指的是当有多个用户请求同一个数据时，会选举出一个 leader 去数据源加载数据，其它用户则等待其拿到的数据。并由 leader 将数据写入缓存。

**Comment by qiujiayu** [comment]
代码在： https://github.com/qiujiayu/AutoLoadCache/blob/master/src/main/java/com/jarvis/cache/DataLoader.java 中的 loadData()。

**Comment by yufenggao** [comment]
谢谢大牛指导




------------------ 原始邮件 ------------------
发件人: "qiujiayu"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 上午10:12
收件人: "qiujiayu/AutoLoadCache"<AutoLoadCache@noreply.github.com>; 
抄送: "高毓锋"<582981557@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [qiujiayu/AutoLoadCache] 拿来主交机制中，多个请求并发访问redis，怎么保证只选取一个leader去更新缓存 (#72)




代码在： https://github.com/qiujiayu/AutoLoadCache/blob/master/src/main/java/com/jarvis/cache/DataLoader.java 中的 loadData()。
