### ISSUE TITLE
我有个场景，批量请求，magic模式下，当返回值不为null时再缓存，否则不缓存，这个怎么写了？

### ISSUE THREAD

**Issue by winds-baby** [qiujiayu/AutoLoadCache#75]

**Comment by qiujiayu** [comment]
https://github.com/qiujiayu/autoload-cache-spring-boot-starter/blob/master/src/test/java/com/jarvis/cache/demo/service/UserServiceImpl.java

这里有一些例子，参考一下。 

建议返回值为null，也要缓存，否则会出现缓存穿透问题。
