### ISSUE TITLE
关于管理页面绑定spring的问题

### ISSUE THREAD

**Issue by Rekoe** [qiujiayu/AutoLoadCache#8]
这个页面对spring的依赖太紧了 导致 还需要引入spring的环境
作者可以参考druid的管理页面来调整下这个功能

**Comment by qiujiayu** [comment]
我看druid 都是通过单例来实现的，具体细节没有去研究，比如：多数据源的情况是怎么来获取相关的数据的。
我现在能想到的办法就是添加 CacheManagerConfig 接口，并通过反射获取其实现。代码已经提交了，如果你有更好的想法，你可以把代码提上去。

**Comment by qiujiayu** [comment]
我们还要考虑，有些系统，会使用多套缓存的情况。

**Comment by Rekoe** [comment]
整合后的管理页面 没有缓存信息
![image](https://cloud.githubusercontent.com/assets/1396322/14940246/48a8c336-0fa0-11e6-8ed7-9c51cee07ce7.png)

**Comment by Rekoe** [comment]
跟踪了一下 发现有个线程里定时更新AutoLoadHandler的对象和
AdminServlet中管理的AutoLoadHandler对象不是同一个 导致的
