### ISSUE TITLE
不支持jedis3.2，升级一个版本呗

### ISSUE THREAD

**Issue by qy8502** [qiujiayu/AutoLoadCache#84]
JedisClusterPipeline中引用的redis.clients.util.SafeEncoder在jedis3.2中挪地方了

拉个分支7.1.x用jedis3.2 ，7.0.x还用jedis2.9也行呀。现在想升级spring-data-redis:2.2.x升不了，它不支持jedis2.9。

**Comment by qiujiayu** [comment]
spring boot 默认推荐使用lettuce，所以你可以先使用lettuce试试。

**Comment by achenbj** [comment]
Factory method 'autoLoadCacheDistributedLock' threw exception; nested exception is java.lang.ClassCastException: org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory cannot be cast to org.springframework.data.redis.connection.jedis.JedisConnectionFactory
使用lottuce会报这个错误,只能用Jedis,Jedis不支持3.X

**Comment by qiujiayu** [comment]
在 #90 中解决
