### ISSUE TITLE
MagicHandler.magic的一个NPE

### ISSUE THREAD

**Issue by hubeicaolei** [qiujiayu/AutoLoadCache#87]
![image](https://user-images.githubusercontent.com/6701735/77281663-98d9e380-6d02-11ea-8102-2225c8e60b4f.png)
这里如果报redis连接异常，会导致返回一个null，在168行报NullPointerException

**Comment by hubeicaolei** [comment]
issue版本是7.0.8

**Comment by qiujiayu** [comment]
有详细的错误信息吗？

**Comment by qiujiayu** [comment]
CacheHandler 构造方法中增加null检查了。

https://github.com/qiujiayu/AutoLoadCache/commit/53be904059ec7bf7d7d7b68c98cb5aa0302f2d49

**Comment by hubeicaolei** [comment]
我的意思是如果在运行过程，redis挂了或者网络断了或者连接超时等等，在SpringRedisCacheManager的155行，return cacheManager.deserialize(keys, redisConnection.closePipeline(), returnType); 就会返回一个null，导致MagicHandler 166行的mget也会返回一个null，导致在168行报npe，导致magic后续的操作全部中断

**Comment by qiujiayu** [comment]
https://github.com/qiujiayu/AutoLoadCache/commit/6facc33327160d5b003bd21a06532de040fcdcc6

已经把 `return null ` 改成 `return Collections.emptyMap()`
