### ISSUE TITLE
能否通过API的方式，而不是通过注解创建一个缓存

### ISSUE THREAD

**Issue by coolyujiyu** [qiujiayu/AutoLoadCache#93]
类似于jetcache这种
https://github.com/alibaba/jetcache/wiki/CreateCache_CN

或者j2cache这种
`CacheChannel cache = J2Cache.getChannel();
cache.set("default", "1", "Hello J2Cache");
cache.evict("default", "1");
cache.close();`

我在AutoLoadCache里面没有找到手工操作的地方

**Comment by qiujiayu** [comment]
可以使用 ICacheManager 来手动操作缓存。
