### ISSUE TITLE
7.0.8版 cache注解缓存是否有问题

### ISSUE THREAD

**Issue by zhangyan1030** [qiujiayu/AutoLoadCache#99]
com.jarvis.cache.DataLoader#doFirstRequest

**Comment by zhangyan1030** [comment]
![image](https://user-images.githubusercontent.com/54790977/101755035-603b9d80-3b0f-11eb-8d8f-dd4d63554671.png)

**Comment by zhangyan1030** [comment]
if (throwable != null) {
            getData();
        }
这块代码 当null != distributedLock && cache.lockExpire() > 0条件不满足时 判断异常非空才会执行取数逻辑 是否不对

**Comment by qiujiayu** [comment]
是有问题的，请使用 7.2.0版本。
